version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: dockerStrongPwd123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Data/DatabaseQueries:/scripts
    networks:
      - app-network
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 20 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P dockerStrongPwd123 -i /scripts/CreateCodingSessionsTable.sql &&
      tail -f /dev/null
      "

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codingtracker-app
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DatabaseConnection: Server=sqlserver,1433;Database=CodingTracker;User=sa;Password=dockerStrongPwd123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
